config/routes.rb
Devise::Application.routes.draw do
  devise_for :users
  root "pages#index"
  get "pages/index"
  get "pages/show"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:full_name, :short_name]
    devise_parameter_sanitizer.for(:account_update) << [:full_name, :short_name]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <%= stylesheet_link_tag    "application", media: "all",
        "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application",
        "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav>
        <% if user_signed_in? %>
          <strong><%= link_to current_user.full_name, pages_show_path %></strong>
          <%= link_to 'Change Profile', edit_user_registration_path %>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path %>
          <%= link_to 'Log In', new_user_session_path %>
        <% end %>
      </nav>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

<%= debug current_user %>